tap "azure/kubelogin"
tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
# brew "ansible"
# brew "asdf"
# brew "azure-cli"
# brew "commitlint"
brew "eza"
# brew "fzf"
# brew "gh"
# brew "mas"
# brew "pre-commit"
# brew "sevenzip"
# brew "starship"
# brew "stow"
brew "thefuck"
brew "zsh-syntax-highlighting"
# cask "appcleaner"
# cask "bitwarden"
# cask "brave-browser"
# cask "clickup"
# cask "docker"
# cask "flux"
# cask "font-fira-code-nerd-font"
# cask "font-jetbrains-mono-nerd-font"
# cask "libreoffice"
# cask "microsoft-auto-update"
# cask "reverso"
# cask "signal"
# cask "slack"
# cask "tempbox"
# cask "visual-studio-code"
# cask "vlc"
# cask "warp"
# cask "zoom"
# mas "LetsView", id: 1478202069
# mas "reMarkable", id: 1276493162
# vscode "4ops.terraform"
# vscode "eamodio.gitlens"
# vscode "ms-vscode-remote.remote-containers"
# vscode "piotrpalarz.vscode-gitignore-generator"
# vscode "yzhang.markdown-all-in-one"
# vscode "zhuangtongfa.material-theme"
